In [1]:
import numpy as np

In [2]:
npArray = np.zeros((5,6))

In [3]:
print(npArray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
print(npArray.dtype)

float64


In [5]:
print(npArray.shape)

(5, 6)


In [6]:
print("Number of rows in array = {}".format(npArray.shape[0]))
print("Number of columns in array = {}".format(npArray.shape[1]))

Number of rows in array = 5
Number of columns in array = 6


In [7]:
npArray = np.zeros((5,6), dtype=np.uint8)

In [8]:
print(npArray)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [9]:
print(npArray.dtype)

uint8


In [10]:
print(npArray.shape)

(5, 6)


In [11]:
print("Number of rows in array = {}".format(npArray.shape[0]))
print("Number of columns in array = {}".format(npArray.shape[1]))

Number of rows in array = 5
Number of columns in array = 6


In [12]:
npArray = np.ones((5,6), dtype=np.uint8)

print(npArray)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [13]:
print(npArray.dtype)
print(npArray.shape)

uint8
(5, 6)


In [14]:
print("Number of rows in array = {}".format(npArray.shape[0]))
print("Number of columns in array = {}".format(npArray.shape[1]))

Number of rows in array = 5
Number of columns in array = 6


In [15]:
npArray = np.random.rand(5,6)

In [16]:
print(npArray)

[[0.19959385 0.36014215 0.8687727  0.03460717 0.66908867 0.65924373]
 [0.18098379 0.75098049 0.85627628 0.09379154 0.86269739 0.91590054]
 [0.79175856 0.24177746 0.95465331 0.34505896 0.49370488 0.06673543]
 [0.54195549 0.59927631 0.30597663 0.1569594  0.09029267 0.24362439]
 [0.01368384 0.84902871 0.02571856 0.97014665 0.38342116 0.70014051]]


In [17]:
print(npArray.dtype)
print(npArray.shape)

float64
(5, 6)


In [18]:
print("Number of rows in array = {}".format(npArray.shape[0]))
print("Number of columns in array = {}".format(npArray.shape[1]))

Number of rows in array = 5
Number of columns in array = 6


In [19]:
npArray = np.array([[1,2,3,4,5,6],
                   [7,8,9,10,11,12],
                   [13,14,15,16,17,18],
                   [19,20,21,22,23,24],
                   [25,26,27,28,29,30]],
                  dtype=np.uint8)

print(npArray)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [20]:
print(npArray.dtype)
print(npArray.shape)

print("Number of rows in array = {}".format(npArray.shape[0]))
print("Number of columns in array = {}".format(npArray.shape[1]))

uint8
(5, 6)
Number of rows in array = 5
Number of columns in array = 6
