# Import libraries

In [1]:
import open3d as o3d
import numpy as np

# create a 3D function

In [2]:
# create evenly spaced numbers over a interval.
x = np.linspace(-4, 4, 400)

In [3]:
# create a rectangular grid
mesh_x, mesh_y = np.meshgrid(x, x)

In [4]:
# create a sinc function
sinc = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))

In [5]:
# normalize sinc (range of sinc is 0 to 1)
norm_sinc = (sinc - sinc.min()) / (sinc.max() - sinc.min())

In [6]:
# initialize a zero matrix and assign value of mesh values and norm_sinc to each column of matrix
matrix = np.zeros((np.size(mesh_x), 3))
matrix[:, 0] = np.reshape(mesh_x, -1)
matrix[:, 1] = np.reshape(mesh_y, -1)
matrix[:, 2] = np.reshape(norm_sinc, -1)

# create a point cloud and write it in a file

In [7]:
# instantiate a point cloud class
point_cloud = o3d.geometry.PointCloud()

# convert a 2D array into 3D format
point_cloud.points = o3d.utility.Vector3dVector(matrix)

In [8]:
# write the point cloud in a file
o3d.io.write_point_cloud("matrix.pcd", point_cloud)

True

# read point cloud file and display it

In [9]:
load_point_cloud = o3d.io.read_point_cloud("matrix.pcd")
o3d.visualization.draw_geometries([load_point_cloud])

In [10]:
# access point cloud values using numpy array
print(np.asarray(load_point_cloud.points))

[[-4.         -4.          0.17846423]
 [-3.97994995 -4.          0.1745076 ]
 [-3.95989966 -4.          0.17150612]
 ...
 [ 3.95989966  4.          0.17150612]
 [ 3.97994995  4.          0.1745076 ]
 [ 4.          4.          0.17846423]]


In [11]:
# save z norm as an image
image = o3d.geometry.Image((norm_sinc*255).astype(np.uint8))
o3d.io.write_image("sinc.png", image)

True